---
ID: "d5d34d11-4e79-405e-bbc6-21756ea7a1d8"
Parent: "6a5b626d-dd5f-464f-b3dc-704af9e9f26e"
Template: "6a5b626d-dd5f-464f-b3dc-704af9e9f26e"
Path: /sitecore/templates/Project/Loreal/Brand Sites/Cerave/Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240301T094345Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1989f9cc-a668-4d08-a5e0-6b73de795977"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240301T094345Z
